### PR TITLE
(improvement) Settings modal appearance tab

### PR DESCRIPTION
**Pull request by Blaumaus**
ASANA Ticket: A[dd Settings/Appearance](https://app.asana.com/0/1201848935859401/1201940285421434/f)

UI Demonstration:
Screenshot from 2022-03-10 15-51-17

### CODE REVIEW

**Comment by hm-bfx** [comment]
Review typo "language" instead of "Langugage"

**Review by bhoomij — COMMENTED** [review]
looks good, along with this can we now also show Settings modal in hosted app too ? may be just with Appearance tab ?

**Comment by hm-bfx** [comment]
Maybe we can wait until we define how to store the keys/password thing. Then we can add a logout button as well (will add to figma)

**Comment by Blaumaus** [comment]
@bhoomij sure, then i'll work on showing settings tab too in this PR

**Comment by Blaumaus** [comment]
The settings modal view on the Web version of the HF:
Screenshot from 2022-03-10 20-11-12

**Comment by bhoomij** [comment]
@Blaumaus please help resolve conflicts for this PR

**Review by bhoomij — APPROVED** [review]

**Pull request merged**
