### PR TITLE
(fix) 'Bad Connection' modal not showing up on Electron app

### PR DESCRIPTION
**Pull request by Blaumaus**
ASANA Ticket: [[bug] the disconnect info modal not always show up on connectivity issues](https://app.asana.com/0/1125859137800433/1201017008819479/f)
Issue: bitfinexcom/bfx-hf-ui#592

For Electron users, the 'Bad Connection' modal was not showing up because of local API and Data servers being used, so when the user was having internet problems, it had no effect on the localhost connection.
This is why a new websocket connection for Electron users has been added.

UI Demonstration:
Screenshot from 2021-09-23 15-58-20

### CODE REVIEW

**Comment by bhoomij** [comment]
@Blaumaus I wanted to try this PR locally first to see if we could use some helper fn of ufx/bfx-containers. But I could not login/reset pw, looks like I am not proceeding because of following check. Please help fix it

`  const offline = Object.keys(sockets).some(s => sockets[s].status !== 'online')`

socket state
`{
bfx-hf-data-server: {status: 'online', lastActivity: 1632583164577}
bfx-hf-server: {status: 'online', lastActivity: 1632583164573}
bfx-wss-pub-server: {status: 'offline', lastActivity: null}
}`

**Comment by pointops** [comment]
Thank you for addressing this!

**Comment by Blaumaus** [comment]
> @Blaumaus I wanted to try this PR locally first to see if we could use some helper fn of ufx/bfx-containers. But I could not login/reset pw after using this branch, looks like I am not proceeding because of following check. Please help fix it
> 
> ` const offline = Object.keys(sockets).some(s => sockets[s].status !== 'online')`
> 
> socket state
> `{ bfx-hf-data-server: {status: 'online', lastActivity: 1632583164577} bfx-hf-server: {status: 'online', lastActivity: 1632583164573} bfx-wss-pub-server: {status: 'offline', lastActivity: null} }`

fixed

**Comment by bhoomij** [comment]
> > @Blaumaus I wanted to try this PR locally first to see if we could use some helper fn of ufx/bfx-containers. But I could not login/reset pw after using this branch, looks like I am not proceeding because of following check. Please help fix it
> > ` const offline = Object.keys(sockets).some(s => sockets[s].status !== 'online')`
> > socket state
> > `{ bfx-hf-data-server: {status: 'online', lastActivity: 1632583164577} bfx-hf-server: {status: 'online', lastActivity: 1632583164573} bfx-wss-pub-server: {status: 'offline', lastActivity: null} }`
> 
> fixed

sorry for delayed reply. 
when I tried with latest pull, still ping-worker is not working since it always return from readyState check (https://github.com/bitfinexcom/bfx-hf-ui-core/blob/main/src/redux/middleware/ws/index.js#L70:L72)

I have proposed a solution in following PR using `getWSConencted` selector from ufx-ui/bfx-containers.
getWSConencted already reflects state of `REACT_APP_UFX_WSS_URL` , and it is pinged already from wsPingSaga of bfx-containers.
@Blaumaus could you please review PR  https://github.com/Blaumaus/bfx-hf-ui-core/pull/1  ?

**Comment by bhoomij** [comment]
closing since implemented in https://github.com/bitfinexcom/bfx-hf-ui-core/pull/107

**Pull request closed without merging**
