### PR TITLE
(fix) not possible to scroll to top after tour is finished

### PR DESCRIPTION
**Pull request by bhoomij**
[not possible to scroll to top after tour is finished](https://app.asana.com/0/1200372033300327/1201567589018006)

### CODE REVIEW

**Comment by dmytroshch** [comment]
need to remove lazy loading of StrategyEditor because tour is not working on this page

**Comment by bhoomij** [comment]
> need to remove lazy loading of StrategyEditor because tour is not working on this page

yes, but it's not related to this PR, also it happens on market-data page too intermittently, I fixed the issue earlier for trading-page by delaying tour-active flag, [here](https://github.com/bitfinexcom/bfx-hf-ui-core/pull/213/files)

**Comment by bhoomij** [comment]
> > need to remove lazy loading of StrategyEditor because tour is not working on this page
> 
> yes, but it's not related to this PR, also it happens on market-data page too intermittently, I fixed the issue earlier for trading-page by delaying tour-active flag, [here](https://github.com/bitfinexcom/bfx-hf-ui-core/pull/213/files)

@dmytroshch could you try https://github.com/bitfinexcom/bfx-hf-ui-core/pull/213/files for market-data/strategy page and create PR if it works good

**Comment by dmytroshch** [comment]
@bhoomij ok

**Pull request merged**
