### PR TITLE
(chore) support CI_ENVIRONMENT_NAME env for hosted version

### PR DESCRIPTION
**Pull request by bhoomij**
[Support CI_ENVIRONMENT_NAME for staging/production mode](https://app.asana.com/0/0/1200659025370578/f)

Description
- by default (or when CI_ENVIRONMENT_NAME=production), start/build scripts will run with production urls
- when CI_ENVIRONMENT_NAME=staging, start/build scripts will run with staging urls

### CODE REVIEW

**Review by dmytroshch — APPROVED** [review]

**Review by JasonMHasperhoven — APPROVED** [review]

**Comment by JasonMHasperhoven** [comment]
Removing all these env vars in the scripts and have them use a .env file would be even better.

**Comment by bhoomij** [comment]
> Removing all these env vars in the scripts and have them use a .env file would be even better.

right, but our deployment process will only set single env variable CI_ENVIRONMENT_NAME, and others envs we have set internally in project as per [this post ](https://bitfinex.slack.com/archives/C06BZ45PC/p1607960154139000)

**Comment by JasonMHasperhoven** [comment]
We can do it later, but at our entry we could create a mapping based on CI_ENVIRONMENT_NAME.

**Comment by bhoomij** [comment]
> > Removing all these env vars in the scripts and have them use a .env file would be even better.
> 
> right, but our deployment process will only set single env variable CI_ENVIRONMENT_NAME, and others envs we have to set internally in project as per [this post ](https://bitfinex.slack.com/archives/C06BZ45PC/p1607960154139000)

moved to .env-cmdrc with help of [env-cmd](url) package

**Review by JasonMHasperhoven — APPROVED** [review]

**Pull request merged**
