### PR TITLE
(improvement) Added OrderForm conneting modal & fixed overlap

### PR DESCRIPTION
**Pull request by Blaumaus**
ASANA Ticket: [[bug] Overlap of "disconnected modal" and order form](https://app.asana.com/0/1125859137800433/1201017008819470/f)
Issue: bitfinexcom/bfx-hf-ui#592

**As Bhoomi proposed, before merging the PR a new `sufficientPermissions` key should be added to the `data.api_credentials.validation` response.**

 - Added 'Connecting' modal which indicates the API client connection state instead of showing fake 'Unconfigured' modal
 - Fixed OrderForm overlap by adding `showOrderform` check

Screenshot from 2021-09-21 13-52-34

### CODE REVIEW

**Comment by pointops** [comment]
Kind request to update 

https://github.com/bitfinexcom/bfx-hf-ui/blob/master/README.md

to advise what the "sufficient permissions" actually are.

much appreciated,
miro

**Review by bhoomij — APPROVED** [review]

**Comment by bhoomij** [comment]
> Kind request to update
> 
> https://github.com/bitfinexcom/bfx-hf-ui/blob/master/README.md
> 
> to advise what the "sufficient permissions" actually are.
> 
> much appreciated,
> miro

@tarcisiozf please help document this.

**Comment by tarcisiozf** [comment]
@bhoomij the current permissions list is:

```
{
  'orders.read': 'Get orders and statuses',
  'orders.write': 'Create and cancel orders',
  'wallets.read': 'Get wallet balances and addresses'
}
```

the values are the labels presented on api manager UI.

**Comment by bhoomij** [comment]
> Kind request to update
> 
> https://github.com/bitfinexcom/bfx-hf-ui/blob/master/README.md
> 
> to advise what the "sufficient permissions" actually are.
> 
> much appreciated,
> miro

@pointops documented [here](https://github.com/bitfinexcom/bfx-hf-ui#api-key-permissions)

**Comment by pointops** [comment]
> 
> {
>   'orders.read': 'Get orders and statuses',
>   'orders.write': 'Create and cancel orders',
>   'wallets.read': 'Get wallet balances and addresses'
> }

> @pointops documented [here](https://github.com/bitfinexcom/bfx-hf-ui#api-key-permissions)

Thanks. 

I note with interest *Margin trading: Get position and margin info* is not listed. Is that not needed for the data normally displayed 
here?


obrazek

**Pull request merged**
