### PR TITLE
(fix) Display strategies irrespective of the beta flag

### PR DESCRIPTION
**Pull request by Blaumaus**
### Asana task:
[(bug) Strategies are not beta features anymore](https://app.asana.com/0/1201849173362898/1203097856141613/f)

### Description:
Now strategies are available for all Honey electron-version users.

### CODE REVIEW

**Review by dmytroshch — APPROVED** [review]

**Review by bhoomij — COMMENTED** [review]
I believe this should be done from backend, that was idea and discussion with @avsek477 to on/off these flags as when we move things in/out of beta flags.

**Review by bhoomij — CHANGES_REQUESTED** [review]
should be done from backend IMO

**Comment by avsek477** [comment]
Yep, I just have to change these fields as required. Let me know what fields to return as what and I will change it accordingly.
https://github.com/bitfinexcom/bfx-hf-server/blob/master/config/feature_flags.json

**Comment by bhoomij** [comment]
> Yep, I just have to change these fields as required. Let me know what fields to return as what and I will change it accordingly. https://github.com/bitfinexcom/bfx-hf-server/blob/master/config/feature_flags.json

@avsek477 enable all of them

**Comment by avsek477** [comment]
https://github.com/bitfinexcom/bfx-hf-server/pull/207

**Pull request closed without merging**
